#%RAML 1.0 NamedExample
request:
      LastModifiedDate: '2021-12-23T13:41:06.000Z'
      Languages__c: English
      AccountId: 0015f00000CFHawAAH
      Email: a_young@dickenson.com
      MobilePhone: "(785) 265-5350"
      Name: Andy Young2223212
      Department: Internal Operations
      OtherLongitude:
      CreatedById: 0055f000004kERuAAM
      MailingLatitude:
      OtherCity: Lawrence
      PhotoUrl:
      MasterRecordId:
      IndividualId:
      IsDeleted: false
      OtherGeocodeAccuracy:
      IsEmailBounced: false
      LastViewedDate:
      MailingCity: Lawrence
      Birthdate: '1978-12-25T00:00:00.000Z'
      OtherStreet: 1301 Hoch Drive
      CleanStatus: '5'
      OtherLatitude:
      LeadSource: Purchased List
      CreatedDate: '2021-11-11T11:06:45.000Z'
      OtherAddress:
        OtherGeocodeAccuracy:
        OtherLatitude:
        OtherLongitude:
        OtherCity: Lawrence
        OtherPostalCode: '66045'
        OtherCountry: USA
        OtherStreet: 1301 Hoch Drive
        OtherState: KS
      LastName: Young2223212
      Id: 0035f000009aOJgAAM
      MailingStreet: 1301 Hoch Drive
      Jigsaw:
      AssistantPhone:
      EmailBouncedDate:
      OtherPhone:
      AssistantName:
      MailingCountry: USA
      LastReferencedDate:
      OtherState: KS
      Salutation: Mr
      MailingState: KS
      Level__c: Primary
      OwnerId: 0055f000004kERuAAM
      MailingLongitude:
      Phone: "(785) 241-6200"
      MailingPostalCode: '66045'
      OtherCountry: USA
      LastCUUpdateDate:
      MailingGeocodeAccuracy:
      EmailBouncedReason:
      FirstName: Andy
      OtherPostalCode: '66045'
      Title: SVP, Operations
      MailingAddress:
        MailingLatitude:
        MailingLongitude:
        MailingPostalCode: '66045'
        MailingCountry: USA
        MailingCity: Lawrence
        MailingGeocodeAccuracy:
        MailingStreet: 1301 Hoch Drive
        MailingState: KS
      LastCURequestDate:
      SystemModstamp: '2021-12-23T13:41:06.000Z'
      HomePhone:
      ReportsToId:
      LastActivityDate:
      Fax:
      LastModifiedById: 0055f000004kERuAAM
      JigsawContactId:
