#%RAML 1.0 NamedExample
response:
  data:
    StatusMessage: "Request has been received"
    RequestId: "2294738"
  error:
    description: "Missing required header - x-api-correlation-id"
    code: 'API_GET_001'
    timestamp: "2021-12-15T15:13:10"